bobMinimumVersion: "1.0"

# Keep ssh-agent working.
layersWhitelist: ["SSH_AGENT_PID", "SSH_AUTH_SOCK"]

layers:
  - name: basement
    scm: git
    url: https://github.com/BobBuildTool/basement.git
    commit: 97798dacc19b51e33558fd6415b2c635dfce0131
    branch: master

  - name: basement-gnu-linux
    scm: git
    url: https://github.com/BobBuildTool/basement-gnu-linux.git
    commit: 7c2d05cc6f50f43e81134286c2b17392ee688d51
    branch: master

  - name: ada
    scm: git
    url: git@git.codelabs.ch:bob/ada.git
    branch: main
    commit: 2e7df443980e83c6e20fd1e708b83888bb776426

  - name: codelabs
    scm: git
    url: git@git.codelabs.ch:bob/codelabs.git
    branch: main
    commit: 0ac8e2a83222a5fa3e50af0fb33de7c674acc2a4
