bobMinimumVersion: "1.0"

# Keep ssh-agent working.
layersWhitelist: ["SSH_AGENT_PID", "SSH_AUTH_SOCK"]

layers:
  - name: basement
    scm: git
    url: https://github.com/BobBuildTool/basement.git
    commit: ee0ce4d7a5a3e8cd1eb14609a14b7605f415154b
    branch: master

  - name: basement-gnu-linux
    scm: git
    url: https://github.com/BobBuildTool/basement-gnu-linux.git
    commit: 7c2d05cc6f50f43e81134286c2b17392ee688d51
    branch: master

  - name: ada
    scm: git
    url: git@git.codelabs.ch:bob/ada.git
    branch: main
    commit: 0aa33360d2b1323b9ab8efe3f6c0c8d7e8dcbceb

  - name: codelabs
    scm: git
    url: git@git.codelabs.ch:bob/codelabs.git
    branch: main
    commit: 0ac8e2a83222a5fa3e50af0fb33de7c674acc2a4
