bobMinimumVersion: "1.1.0rc1"

# Keep ssh-agent working.
layersWhitelist: ["SSH_AGENT_PID", "SSH_AUTH_SOCK"]

layers:
  - name: basement
    scm: git
    url: https://github.com/BobBuildTool/basement.git
    commit: b79927c309a08bfd6daed00385a88576bad5310d
    branch: master

  - name: basement-gnu-linux
    scm: git
    url: https://github.com/BobBuildTool/basement-gnu-linux.git
    commit: c1d98bf23f1f86bf37220ff956dbccd5094f66b9
    branch: master

  - name: ada
    scm: git
    url: https://git.codelabs.ch/bob/ada.git
    branch: main
    commit: 11f6c306f6e03dfd019c8e8108a3283b01a4a7fd

  - name: codelabs
    scm: git
    url: https://git.codelabs.ch/bob/codelabs.git
    branch: main
    commit: 0ac8e2a83222a5fa3e50af0fb33de7c674acc2a4
