bobMinimumVersion: "0.25.0"

# Keep ssh-agent working.
layersWhitelist: ["SSH_AGENT_PID", "SSH_AUTH_SOCK"]

layers:
  - name: basement
    scm: git
    url: https://github.com/BobBuildTool/basement.git
    commit: fff9d8d0c454ac70d9edf6b0321b2da33d5e9a64
    branch: master

  - name: basement-gnu-linux
    scm: git
    url: https://github.com/BobBuildTool/basement-gnu-linux.git
    commit: eadb4ef1ece46de2a999d9526009e3b55a968901
    branch: master

  - name: ada
    scm: git
    url: git@git.codelabs.ch:bob/ada.git
    branch: main
    commit: af28817d6f38bc0ab4210547eb4b00793b388bfe

  - name: codelabs
    scm: git
    url: git@git.codelabs.ch:bob/codelabs.git
    branch: main
    commit: 9a5dcdc3f4e348432d6b86616b725962e6c07bfd
