bobMinimumVersion: "0.25.0"

# Keep ssh-agent working.
layersWhitelist: ["SSH_AGENT_PID", "SSH_AUTH_SOCK"]

layers:
  - name: basement
    scm: git
    url: https://github.com/BobBuildTool/basement.git
    commit: 287f937d683b01cd2f4b4fb4bba5f0c1396ad2f2
    branch: master

  - name: basement-gnu-linux
    scm: git
    url: https://github.com/BobBuildTool/basement-gnu-linux.git
    commit: 19b126d870d341de4c0898005e3e61cbaf8c21c0
    branch: master

  - name: ada
    scm: git
    url: git@git.codelabs.ch:bob/ada.git
    branch: main
    commit: f2c47aca5ac3981973923f2a43e531b4884d63f9

  - name: codelabs
    scm: git
    url: git@git.codelabs.ch:bob/codelabs.git
    branch: main
    commit: 9a5dcdc3f4e348432d6b86616b725962e6c07bfd
