bobMinimumVersion: "1.1.0rc1"

# Keep ssh-agent working.
layersWhitelist: ["SSH_AGENT_PID", "SSH_AUTH_SOCK"]

layers:
  - name: basement
    scm: git
    url: https://github.com/BobBuildTool/basement.git
    commit: ee0ce4d7a5a3e8cd1eb14609a14b7605f415154b
    branch: master

  - name: basement-gnu-linux
    scm: git
    url: https://github.com/BobBuildTool/basement-gnu-linux.git
    commit: 1f9be7ea25154bdc6539b439931e260f464ad345
    branch: master

  - name: ada
    scm: git
    url: git@git.codelabs.ch:bob/ada.git
    branch: main
    commit: b29ffe07c36a80717365a66dca93916d4509d179

  - name: codelabs
    scm: git
    url: git@git.codelabs.ch:bob/codelabs.git
    branch: main
    commit: 0ac8e2a83222a5fa3e50af0fb33de7c674acc2a4
